<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>WinFormsApp1</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Metodos Numericos\Metodos Numericos.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="MainForm.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

</Project>